package partg;

/**
 *
 * @author Jordan Hennell n8331472
 * @author Michael Clark n8583331
 */
public class PartG extends javax.swing.JFrame {

    /**
     * Creates new form PartG
     */
    public PartG() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        circuitBoard1 = new Digital.CircuitBoard();
        bitAdderComponent1 = new Digital.BitAdderComponent();
        switch1 = new Digital.Switch();
        switch2 = new Digital.Switch();
        switch3 = new Digital.Switch();
        lED1 = new Digital.LED();
        lED2 = new Digital.LED();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        circuitBoard1.setLayout(null);

        bitAdderComponent1.setInput0(switch1.getOutput());
        bitAdderComponent1.setInput1(switch2.getOutput());
        bitAdderComponent1.setInput2(switch3.getOutput());

        javax.swing.GroupLayout bitAdderComponent1Layout = new javax.swing.GroupLayout(bitAdderComponent1);
        bitAdderComponent1.setLayout(bitAdderComponent1Layout);
        bitAdderComponent1Layout.setHorizontalGroup(
            bitAdderComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        bitAdderComponent1Layout.setVerticalGroup(
            bitAdderComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        circuitBoard1.add(bitAdderComponent1);
        bitAdderComponent1.setBounds(270, 170, 48, 31);
        circuitBoard1.add(switch1);
        switch1.setBounds(130, 110, 35, 39);
        circuitBoard1.add(switch2);
        switch2.setBounds(130, 170, 35, 39);
        circuitBoard1.add(switch3);
        switch3.setBounds(130, 230, 35, 39);

        lED1.setInput(bitAdderComponent1.getOutput0());

        javax.swing.GroupLayout lED1Layout = new javax.swing.GroupLayout(lED1);
        lED1.setLayout(lED1Layout);
        lED1Layout.setHorizontalGroup(
            lED1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        lED1Layout.setVerticalGroup(
            lED1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        circuitBoard1.add(lED1);
        lED1.setBounds(440, 110, 30, 35);

        lED2.setInput(bitAdderComponent1.getOutput1());

        javax.swing.GroupLayout lED2Layout = new javax.swing.GroupLayout(lED2);
        lED2.setLayout(lED2Layout);
        lED2Layout.setHorizontalGroup(
            lED2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        lED2Layout.setVerticalGroup(
            lED2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        circuitBoard1.add(lED2);
        lED2.setBounds(440, 220, 30, 35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(circuitBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(circuitBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Digital.BitAdderComponent bitAdderComponent1;
    private Digital.CircuitBoard circuitBoard1;
    private Digital.LED lED1;
    private Digital.LED lED2;
    private Digital.Switch switch1;
    private Digital.Switch switch2;
    private Digital.Switch switch3;
    // End of variables declaration//GEN-END:variables
}
