package Digital;

/**
 *
 * @author Jordan Hennell n8331472
 * @author Michael Clark n8583331
 */
public class Switch extends javax.swing.JPanel {

    // Output value
    public final OutputTerminal output = new OutputTerminal();
    
    /**
     * Creates new form Switch
     */
    public Switch() {
        initComponents();

        // Switch is initially off
        output.setValue(false);
    }

    /**
     * Get the value of output
     *
     * @return the value of output
     */
    public OutputTerminal getOutput() {
        return output;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Digital/images/Switch_off.gif"))); // NOI18N
        jToggleButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButton1.setRolloverEnabled(false);
        jToggleButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Digital/images/Switch_on.gif"))); // NOI18N
        jToggleButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToggleButton1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToggleButton1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton1StateChanged
        // The output value is based on the isSelected property of the JToggleButton
        output.setValue(jToggleButton1.isSelected());
    }//GEN-LAST:event_jToggleButton1StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
